############################
#                          #
#                          #
#        JoinEvents        #
#      by DopeDealers      #
#                          #
#                          #
############################
# Placeholder API support
# HexColor support with default color coding options
# Unlimited rank joins with support to enable to disable them without having to remove them
# To color the bossbar check the link below out
# Unlimited custom join items
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
#
# Actions: msg/heal
# example {msg:Player:'&aHello player i have messaged just you!'}
# example {heal:Player}
# More soon to come.

config:
  database:
    mysql:
      host: localhost
      port: 3306
      database: mydatabase
      username: your_username
      password: your_password
  welcomeMessage:
    enabled: true
    actionBar:
      title:
      subtitle:
      foreverBar:
    display:
      - "temp"
  leaderboard: # for top logins and top time played
    x: 100.0
    y: 70.0
    z: 100.0
    world: world_name
  scoreboard:
    title: "&aMy Scoreboard"
    lines:
      - "&eLine 1"
      - "&6Line 2"
      - "&cLine 3"
  time:
    rewards:
      reward1: # Unique reward ID
        name: "Reward 1" # Name of the reward
        command: "give %player% diamond 1" # Command to execute for the reward
        required-playtime: 174 # Required playtime in minutes
        multiplier:
          mvp: 5 # Multiplier for Rank 1
          rank2: 2.0 # Multiplier for Rank 2
      reward2: # Another unique reward
        name: "Reward 2"
        command: "give %player% gold_ingot 64"
        required-playtime: 240
        multiplier:
          rank1: 2.0
          rank2: 2.5
  ranks:
    mvp:
      enabled: true
      permission: joinevents.rank.mvp
      messages:
        enabled: true
        join: "&7[&6&lMVP&7] &6%player_name% &7Has joined the server!"
        quit: "&7[&6&lMVP&7] &6%player_name% &7Has left the server ):" # Quit message
      noise:
        enabled: true
        sound: "ENTITY_EXPERIENCE_ORB_PICKUP" # Sound for the rank
        volume: 10 # Sound volume
        pitch: 1.5 # Sound pitch
      fireworks:
        enabled: true
        flicker: false
        trail: true
        mainColor: 16777215
        fadeColor: 16777215
        type: "BALL" # Firework type
      joinBook:
        enabled: true
        title: Welcome to the server mvp
        author: "Prisk"
        pages:
          - This is the join message for page 1
          - this is the second page
          - third
          - fourth
      bossBar:
        enabled: true
        color: "WHITE" # Boss bar color
        style: "SOLID" # Boss bar style
        title: "Hello!"
        time: 1 # Boss bar display time
        progress: 1.0 # Boss bar progress
      joinItems:
        compass_1:
          enabled: true
          unmovable: true
          material: "DIAMOND_SWORD" # Item material
          nameTag:
            nbtTagName: "customItem"
            nbtValue: "specialSword"
          name: "&aCustom Sword" # Item name
          lore:
            - "&7This is a custom sword." # Item lore
          slot: 0 # Item slot in the inventory
          enchantments:
            SHARPNESS: 5
            UNBREAKING: 3 # Item enchantments
          uses: 10 # Item uses
          unlimtedUses: false
          cooldown:
            time: "10s" # Cooldown time
            message: "Cooldown: %s"
          commands:
            right_click:
              - "say Welcome, %player_name%, to the server!"
              - "give %player_name% diamond 1" # Commands on right-click
            left_click:
              - "give %player_name% gold_ingot 2" # Commands on left-click
          actions:
            right_click:
              - "{msg:Player:'&6&lHi this is a test friend!'}"
            left_click:
              - "{heal:Player}"
              - "{msg:Player:'&a&lHello &6&l%player_name% &aYou have been healed'}"
